### ISSUE TITLE
No sound notification if enabled

### ISSUE THREAD

**Issue by betteryouthanme** [JoomJunk/shoutbox#157] opened 2015-05-01 18:09 UTC
on live site and on my fresh installation on XAMPP

**Comment by C-Lodder** [comment] 2015-05-01 19:38
@betteryouthanme - Which browser are you using?

The sound notification is only supposed to play if a new shout appears from another user, not your own shouts

**Comment by betteryouthanme** [comment] 2015-05-03 14:11
kk i'm not sure anymore.. tried to send with IE and did not receive the message in Firefox. I always have to refresh page then.
Maybe that's only for me as i have some bugs on "home" page anyway..
![mediafailed](https://cloud.githubusercontent.com/assets/8537297/7445340/9bd2016e-f1ae-11e4-9586-d1310e7e9db9.jpg)

But theres also one regering to the ogg file of shoutbox saying that loading failed.
rprclan.com

**Comment by C-Lodder** [comment] 2015-05-03 21:07
@betteryouthanme - That error usually occurs when the bootstrap.js file has been manually removed or your have disable it another way. If this is the case for you, can you try re-enabling it again. I'll look into the audio issue you mentioned before though

**Comment by C-Lodder** [comment] 2015-05-04 13:14
@betteryouthanme - I can confirm this is an issue. For some reason it works on Protostar but does not work on some other template

**Comment by betteryouthanme** [comment] 2015-06-09 18:26
that refresh is not working for me has to do with the GameServer! module i have installed. Guess because it is also using a refresh method. Seems there's a conflict. The sound bug does not work at all with Purity III as you said.

**Comment by C-Lodder** [comment] 2015-06-09 18:31
It might be due to the "multiple instances" issue we half fixed in a later release. George and myself have haven't had much time to work on any new fixes and feature as we're been very busy recently. We will be making some big changes to the code structure fairly soon

**Comment by C-Lodder** [comment] 2015-09-11 13:44
This now appears to be resolved. I believe it was due to JS conflicts which we've now resolved with namespacing

**Closed by C-Lodder** 2015-09-11 13:44 UTC
